FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set an environment variable where the Rails app is installed to inside of Docker image
ENV RAILS_ROOT /var/www/code
RUN mkdir -p $RAILS_ROOT

# Set working directory
WORKDIR $RAILS_ROOT

# Setting env up
# ENV RAILS_ENV= 'production'
# ENV RACK_ENV='production'


# DB Credentials
# ENV 'BRIDGEKIN_DATABASE_PASSWORD'

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

# if ( ENV RAILS_ENV= 'development')
#  RUN bundle install --jobs 20 --retry 5
# else:
#  RUN bundle install --jobs 20 --retry 5 --without development test

RUN bundle install --jobs 20 --retry 5 --without development test

# RUN echo '{ "allow_root": true }' > /root/.bowerrc

# Adding project files
COPY . .
RUN bundle exec rake assets:precompile

EXPOSE 3000

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
