const termsText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis congue, risus quis ullamcorper maximus, mi ex luctus magna, sit amet dapibus arcu justo a justo. Duis gravida dapibus dignissim. Donec luctus mi ut felis tempor luctus. Vestibulum in gravida dolor, eget convallis nibh. Donec id cursus dui. Quisque tempor accumsan porta. Mauris tristique eros quis ex facilisis, vel varius nunc convallis. Mauris blandit, felis in molestie pellentesque, eros nibh tempus turpis, non suscipit augue mi nec magna. Cras justo tortor, maximus vel dapibus et, congue in massa. Duis sed aliquet ipsum. Cras malesuada, lorem at dapibus tempor, leo mi elementum magna, eget pellentesque neque quam non orci. Nulla sed purus rhoncus, ullamcorper nisl id, cursus tortor. Vivamus dapibus gravida maximus. Praesent ut lectus vitae est pharetra ullamcorper ac quis quam. Phasellus vehicula ex et sapien varius, eu interdum libero tempor.

Donec nulla lacus, consequat id turpis vel, feugiat pulvinar nisl. Mauris varius ullamcorper pellentesque. Morbi elementum eget metus nec dignissim. Ut purus ex, pretium non purus quis, sollicitudin mattis elit. Morbi sed sagittis ex, in rutrum ante. Sed eu bibendum nisl, id cursus mauris. Curabitur est enim, mattis non tempus sed, facilisis laoreet tellus. Donec et elementum nunc. Mauris blandit, dui vel mattis eleifend, leo enim ultricies orci, dapibus pulvinar tortor augue ac elit. Sed elementum tellus ac libero pulvinar, at accumsan erat pharetra. Aenean at sapien orci. Cras consequat turpis non magna tincidunt porta. Mauris metus sem, mattis vitae dolor in, sollicitudin pellentesque justo. Cras porttitor lorem quis cursus semper. Nulla efficitur quam est, nec fringilla augue efficitur vitae.

Maecenas consectetur ante sit amet tincidunt porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque aliquet iaculis eros, eget mattis nibh ultricies eu. Nunc pellentesque dolor sed molestie posuere. Duis feugiat tincidunt mi quis consectetur. Sed lobortis dui sit amet ipsum finibus, ac dapibus augue ultrices. Nam eu erat ac nibh tristique maximus. Sed eget tortor interdum, mollis ligula vitae, efficitur neque. Nullam risus velit, aliquam ac lacus ac, mattis sollicitudin ex. Nunc pretium lobortis vehicula. Pellentesque interdum sit amet libero nec gravida. Morbi a mauris felis. Cras eget condimentum urna. Nunc vehicula risus consectetur ante fermentum, sed consectetur leo condimentum.

Duis at cursus felis, quis blandit leo. Nunc sodales purus nisl, eu fermentum erat bibendum nec. Aliquam tempor magna quis facilisis maximus. Donec pharetra, nisi ut varius mollis, velit tortor malesuada velit, ut aliquam libero magna a dolor. Duis at ullamcorper ex. Sed vel porttitor purus, sit amet ultricies diam. Vestibulum quis fermentum tellus, sed porta ex. In malesuada pharetra metus ut dapibus. Duis id posuere massa.

Maecenas in odio vel ante cursus lobortis vel vel magna. Aliquam tincidunt mattis neque. Vestibulum posuere urna at purus faucibus, et euismod enim fringilla. Donec aliquam lectus vitae lorem pulvinar rutrum. Duis imperdiet porta justo ac facilisis. In pretium suscipit ipsum non molestie. Nulla eu sem non justo pulvinar faucibus in vel enim. Aliquam commodo metus posuere enim fermentum luctus. Maecenas a aliquet nibh. Donec metus purus, convallis non urna quis, ultrices feugiat est. Curabitur consequat arcu non lorem posuere, nec efficitur ante volutpat. Morbi arcu ante, elementum viverra nisl eget, consequat sollicitudin tortor.`

export default termsText;
